[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
evm_version = "london"
optimizer = true
optimizer_runs = 200
remappings = ["forge-std/=lib/forge-std/src/"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

# Configurações para deploy na rede Sepolia
[profile.sepolia]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
evm_version = "london"
optimizer = true
optimizer_runs = 200
# Configurações específicas da rede Sepolia
chain_id = 11155111

